env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

matrix:
  include:
    - os: osx
    - os: linux

language: node_js
node_js: '14'

cache:
  npm: false
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

install:
  - npm install

script:
  - npm run pack
  - npm run dist

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
    - stable
