image: Visual Studio 2017

platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 14 x64
  - npm install

build_script:
  - npm run pack
  - npm run dist

test: off

environment:
  GH_TOKEN:
    secure: rtwqQ0lpjwUxes3Vnn+KGMqTn1CBUnWwoXdksyqUrJdOdN/dmakG7QYf0qPG2Il/

branches:
  only:
    - stable
